name: bot
recipe: lamp
config:
  webroot: public
  php: '7.3'
proxy:
  appserver:
    - bot.local
services:
  databases:
    type: mysql:5.7.24
    portforward: true
tooling:
  php:
    service: appserver
