echo "
APP_KEY=$APP_KEY
APP_URL=$APP_URL
APP_TIMEZONE=$APP_TIMEZONE
DB_CONNECTION=$DB_CONNECTION
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_DATABASE=$DB_DATABASE
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD
TELEGRAM_API_URL=$TELEGRAM_API_URL
TELEGRAM_API_URL=$TELEGRAM_API_URL
" >> .env
